---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu_14.04
    driver_config:
      box: 'ubuntu/trusty64'
      box_url: 'http://files.vagrantup.com/trusty64.box'
      customize:
        memory: 2048
        cpus: 2
suites:
  - name: default
    run_list:
      - recipe[kafka_broker::default]
    attributes:
